### ISSUE TITLE
project refrence seems not work

### ISSUE THREAD

**Issue by timiil** [WeihanLi/dotnet-exec#2]
hi , the project is very good!

but i can not try for a project refrence, steps here:

```
mkdir -p test/alib 
cd test/alib

dotnet new classlib

cd ..

```

create a test.cs in test folder:

```
alib.Class1 inst = new();
Console.WriteLine($"inst = {inst}");
```

and then :

```
dotnet-exec .\test.cs --project .\alib\alib.csproj
fail: dotnet-exec[0]
      Compile error:
      CS0246-Error-(1,1): error CS0246: The type or namespace name 'alib' could not be found (are you missing a using directive or an assembly reference?)

```

anything that i had missed ?

**Comment by WeihanLi** [comment]
Hi, thanks for the report, did you try to reference a project? This is not supported by now.
If your test code relies on other code, you can add additional code via the `--ad`/`--addition` option
For example:

``` sh
dotnet-exec ./test.cs --ad ./alib/Class1.cs
```

**Comment by WeihanLi** [comment]
You can also reference the dll generated

``` sh
dotnet-exec ./test.cs -r ./alib/bin/Debug/alib.dll
```

or

``` sh
dotnet-exec ./test.cs --reference ./alib/bin/Debug/alib.dll
```

**Comment by timiil** [comment]
thanks for reply and detail explaintion :) 谢谢

refrence from a dll may be a little strange because i need to do a 'dotnet build xxxx' command to make the dll real, but not use 'dotnet-exec xxxx' on the fly.

the project is useful, we could use c# like python in some little scene,special for a handy tool in some large project

**Comment by WeihanLi** [comment]
The dll path needs to be converted to an absolute path, would try to add an implicit conversion from the relative path to the absolute path.

For the project reference, would try to add the project reference support in the next release

Thanks very much for the valuable feedback.

**Comment by timiil** [comment]
very happy to know that you may move up these features ! nice job, i should looking forward to wait your upgrade :)

**Comment by WeihanLi** [comment]
Hi @timiil , I had released a preview version [0.11.0-preview-20221120-032905](https://www.nuget.org/packages/dotnet-execute/0.11.0-preview-20221120-032905), could you please have a try, you can update the latest preview release via `dotnet tool update -g dotnet-execute --prerelease`

You can use the `--reference 'project: xxx.csproj'` to reference a project, it looks good from my side

![image](https://user-images.githubusercontent.com/7604648/202900363-dadebd8f-01c4-4921-badf-fb194a8f0f09.png)

**Comment by WeihanLi** [comment]
0.11.0 released

**Comment by WeihanLi** [comment]
Closed since we had added support for project reference, feel free to reopen or create a new issue if any issue

**Comment by timiil** [comment]
sorry for delay :)

i had update the version, it is WORK ! thanks you very much :) 👍 

```
dotnet-exec .\test.cs -r 'project: .\alib\alib.csproj'
```

```
inst = alib.Class1
```
